### ISSUE TITLE
It should not fail when lumping empty group with weight

### ISSUE THREAD

**Issue by holgerbrandl** [hadley/forcats#294] opened 2022-01-12 15:03 UTC
When using `fct_lump` on a grouped data frame with a weighting attribute, it should not fail if a group is empty.

Example
```r
iris %>% 
  group_by(Species) %>% filter(Species == "virginica") %>% 
  mutate(Species_Lumped = forcats::fct_lump(Species, w = Speal.Length, prop = 0.04))
```
This fails using v0.5.1 with 
```
Error: Problem with `mutate()` column `Species_Lumped`.
i `Species_Lumped = forcats::fct_lump(Species, w = Sepal.Length, prop = 0.04)`.
x missing value where TRUE/FALSE needed
i The error occurred in group 1: Species = virginica.
Run `rlang::last_error()` to see where the error occurred
```

Tested with R version 4.1.2 (2021-11-01)

**Comment by xxspurs** [comment] 2022-01-12 15:04
您好，我已收到您的邮件，将尽快给您回复。

**Comment by hadley** [comment] 2022-03-02 15:29
Reprex:

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  group_by(Species) %>% 
  filter(Species == "virginica") %>% 
  mutate(Species_Lumped = forcats::fct_lump(Species, w = Sepal.Length, prop = 0.04))
#> Error in `mutate()`:
#> ! Problem while computing `Species_Lumped = forcats::fct_lump(Species, w
#>   = Sepal.Length, prop = 0.04)`.
#> ℹ The error occurred in group 1: Species = virginica.
#> Caused by error in `if (prop > 0 && sum(prop_n <= prop) <= 1) ...`:
#> ! missing value where TRUE/FALSE needed
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Duplicate of #292

**Closed as completed by hadley** 2022-03-02 15:29 UTC
